-- MySQL Script generated by MySQL Workbench
-- Thu 02 Nov 2017 10:39:28 AM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cdr
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cdr` ;

-- -----------------------------------------------------
-- Schema cdr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cdr` DEFAULT CHARACTER SET utf8 ;
USE `cdr` ;

-- -----------------------------------------------------
-- Table `cdr`.`call_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cdr`.`call_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NULL,
  `company` VARCHAR(255) NULL,
  `dnis` VARCHAR(255) NULL,
  `ani` VARCHAR(255) NULL,
  `calldate` DATETIME NULL,
  `enddate` DATETIME NULL,
  `duration` INT NULL,
  `billsec` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cdr`.`call_details`
-- -----------------------------------------------------
START TRANSACTION;
USE `cdr`;
INSERT INTO `cdr`.`call_details` (`id`, `type`, `company`, `dnis`, `ani`, `calldate`, `enddate`, `duration`, `billsec`) VALUES (1, 'INBOUND', 'OPTUM', '+17635555555', '+18004444444', '2017-10-31 12:34:45', '2017-10-31 12:35:45', 60, 45);
INSERT INTO `cdr`.`call_details` (`id`, `type`, `company`, `dnis`, `ani`, `calldate`, `enddate`, `duration`, `billsec`) VALUES (2, 'OUTBOUND', 'OPTUM', '+12181112222', '+18662223333', '2017-09-30 12:34:45', '2017-09-30 12:35:45', 60, 45);
INSERT INTO `cdr`.`call_details` (`id`, `type`, `company`, `dnis`, `ani`, `calldate`, `enddate`, `duration`, `billsec`) VALUES (3, 'INBOUND', 'OPTUM', '+13201111111', '+13202223333', '2017-08-31 12:34:45', '2017-08-31 12:35:45', 60, 45);
INSERT INTO `cdr`.`call_details` (`id`, `type`, `company`, `dnis`, `ani`, `calldate`, `enddate`, `duration`, `billsec`) VALUES (4, 'OUTBOUND', 'OPTUM', '+15071112222', '+18882223333', '2017-07-30 12:34:45', '2017-07-30 12:35:45', 60, 45);
INSERT INTO `cdr`.`call_details` (`id`, `type`, `company`, `dnis`, `ani`, `calldate`, `enddate`, `duration`, `billsec`) VALUES (5, 'INBOUND', 'OPTUM', '+16121112222', '+16122223333', '2017-06-30 12:34:45', '2017-06-30 12:35:45', 60, 45);
INSERT INTO `cdr`.`call_details` (`id`, `type`, `company`, `dnis`, `ani`, `calldate`, `enddate`, `duration`, `billsec`) VALUES (6, 'OUTBOUND', 'OPTUM', '+16511112222', '+16512223333', '2017-05-30 12:34:45', '2017-05-30 12:35:45', 60, 45);
INSERT INTO `cdr`.`call_details` (`id`, `type`, `company`, `dnis`, `ani`, `calldate`, `enddate`, `duration`, `billsec`) VALUES (7, 'INBOUND', 'OPTUM', '+17631112222', '+17632223333', '2017-07-01 01:01:01', '2017-07-01 01:02:01', 60, 45);
INSERT INTO `cdr`.`call_details` (`id`, `type`, `company`, `dnis`, `ani`, `calldate`, `enddate`, `duration`, `billsec`) VALUES (8, 'OUTBOUND', 'OPTUM', '+19521112222', '+19522223333', '2017-10-15 13:34:34', '2017-10-15 13:35:34', 100, 50);
INSERT INTO `cdr`.`call_details` (`id`, `type`, `company`, `dnis`, `ani`, `calldate`, `enddate`, `duration`, `billsec`) VALUES (9, 'OUTBOUND', 'OPTUM', '+18001112222', '+18002223333', '2017-10-15 13:40:40', '2017-10-15 13:41:50', 10, 5);

COMMIT;

